select * from customer;

--q1 what is the total revenue generated by male vs. female customers7
select gender,sum(purchase_amount) as revenue
from customer
group by gender
--q2- which customers uded a discount but still spent more then the average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >=(select avg(purchase_amount) from customer) 
--q3 which are the top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating::numeric),2)as average_product_rating
from customer 
group by item_purchased
order by avg(review_rating) desc 
limit 5
--Q4 campare the average purchase amounts between standard and express shipping
select avg(purchase_amount) as round
from customer
where shipping_type='Standard'
union all
select  avg(purchase_amount) as round
from customer
where shipping_type='Express'
--q5 do subscribed customers spend more? campare average spend and total revenue between subscribers and non-subscribes
--select round(avg(purchase_amount),2) as avg_spend
select  subscription_status,count(customer_id)as total_customers, round(avg(purchase_amount),2) as avg_spend,sum(purchase_amount) as total_revenue
from customer
where subscription_status in ('Yes','No')
group by subscription_status
order by total_revenue desc
--q6. which  5 products have the highest percentage of purchases with discounts applied
select item_purchased, round(sum(count(item_purchased))100/(select count() from customer),2) as purchase_perc
from customer
where discount_applied='Yes'
group by item_purchased
order by purchase_perc desc
limit 5
*
--q7 segment customers into new , returning , and loyal based on their total
--number of prev purchases and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
case 
    when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*) as"Number of Customers"
from customer_type 
group by customer_segment

--q8what are thr 3 most purchased products within each gategory
select distinct category, count( item_purchased) as freq
from  customer
group by category,item_purchased
order by freq desc
limit 3
--q9what is the revenue contribution of eac age group

select age_group ,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc
SELECT current_user;
SELECT session_user;
